export { Nav } from "./nav";
export { Button } from "./mainPage";
export { FunFacts } from "./about";
export { Projects } from "./portfolio";
export { EmailForm } from "./mainPage";
export { TypeEffect } from "./mainPage";
export { Languages } from "./mainPage";
export { Frameworks } from "./mainPage";
export { LanguagesAndFrameworks } from "./mainPage";
export { Accomplishments } from "./about";
export { default as Footer } from "./Footer";
